// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bill struct {
	ID          int64              `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description string             `json:"description"`
	BillType    int16              `json:"bill_type"`
	Category    int32              `json:"category"`
	RecordDate  pgtype.Timestamptz `json:"record_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
