// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (
    user_id, amount, description, bill_type, category, record_date
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, amount, description, bill_type, category, record_date, created_at, updated_at
`

type CreateBillParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	Amount      decimal.Decimal `json:"amount"`
	Description string          `json:"description"`
	BillType    int16           `json:"bill_type"`
	Category    int32           `json:"category"`
	RecordDate  time.Time       `json:"record_date"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.BillType,
		arg.Category,
		arg.RecordDate,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.BillType,
		&i.Category,
		&i.RecordDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password
) VALUES (
    $1, $2, $3
) RETURNING id, username, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBill = `-- name: DeleteBill :exec
DELETE FROM bills
WHERE id = $1 AND user_id = $2
`

type DeleteBillParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBill(ctx context.Context, arg DeleteBillParams) error {
	_, err := q.db.Exec(ctx, deleteBill, arg.ID, arg.UserID)
	return err
}

const getDailyStats = `-- name: GetDailyStats :many
SELECT 
    record_date::DATE as date, -- 强转为日期，去掉时分秒
    COALESCE(SUM(CASE WHEN bill_type = 2 THEN amount ELSE 0 END), 0)::DECIMAL as daily_income,
    COALESCE(SUM(CASE WHEN bill_type = 1 THEN amount ELSE 0 END), 0)::DECIMAL as daily_expense
FROM bills
WHERE user_id = $1 
  AND record_date >= $2::TIMESTAMPTZ 
  AND record_date <= $3::TIMESTAMPTZ
GROUP BY record_date::DATE
ORDER BY date DESC
`

type GetDailyStatsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

type GetDailyStatsRow struct {
	Date         pgtype.Date    `json:"date"`
	DailyIncome  pgtype.Numeric `json:"daily_income"`
	DailyExpense pgtype.Numeric `json:"daily_expense"`
}

// 首页列表：核心变化在这里
// 我们需要把 record_date 强转为 DATE 类型来分组
func (q *Queries) GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]GetDailyStatsRow, error) {
	rows, err := q.db.Query(ctx, getDailyStats, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyStatsRow
	for rows.Next() {
		var i GetDailyStatsRow
		if err := rows.Scan(&i.Date, &i.DailyIncome, &i.DailyExpense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyStats = `-- name: GetMonthlyStats :one
SELECT 
    COALESCE(SUM(CASE WHEN bill_type = 2 THEN amount ELSE 0 END), 0)::DECIMAL as total_income,
    COALESCE(SUM(CASE WHEN bill_type = 1 THEN amount ELSE 0 END), 0)::DECIMAL as total_expense
FROM bills
WHERE user_id = $1 
  AND record_date >= $2::TIMESTAMPTZ 
  AND record_date <= $3::TIMESTAMPTZ
`

type GetMonthlyStatsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

type GetMonthlyStatsRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
}

// 首页顶部统计：依然是按时间范围查，逻辑不变
func (q *Queries) GetMonthlyStats(ctx context.Context, arg GetMonthlyStatsParams) (GetMonthlyStatsRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyStats, arg.UserID, arg.StartTime, arg.EndTime)
	var i GetMonthlyStatsRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBills = `-- name: ListBills :many
SELECT id, user_id, amount, description, bill_type, category, record_date, created_at, updated_at FROM bills
WHERE user_id = $1
ORDER BY record_date DESC
LIMIT $2 OFFSET $3
`

type ListBillsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListBills(ctx context.Context, arg ListBillsParams) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listBills, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.BillType,
			&i.Category,
			&i.RecordDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBill = `-- name: UpdateBill :one
UPDATE bills
SET 
    amount = $2,
    description = $3,
    bill_type = $4,
    category = $5,
    record_date = $6
WHERE id = $1 AND user_id = $7
RETURNING id, user_id, amount, description, bill_type, category, record_date, created_at, updated_at
`

type UpdateBillParams struct {
	ID          int64           `json:"id"`
	Amount      decimal.Decimal `json:"amount"`
	Description string          `json:"description"`
	BillType    int16           `json:"bill_type"`
	Category    int32           `json:"category"`
	RecordDate  time.Time       `json:"record_date"`
	UserID      uuid.UUID       `json:"user_id"`
}

// sqlc 会自动处理 updated_at (通过数据库触发器)，不需要手动传
func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBill,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.BillType,
		arg.Category,
		arg.RecordDate,
		arg.UserID,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.BillType,
		&i.Category,
		&i.RecordDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
