// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  user_id, name, type, currency, icon, color, status, is_default, sort_order
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, name, type, currency, icon, color, status, is_default, sort_order, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Currency  string      `json:"currency"`
	Icon      []byte      `json:"icon"`
	Color     pgtype.Text `json:"color"`
	Status    string      `json:"status"`
	IsDefault bool        `json:"is_default"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Icon,
		arg.Color,
		arg.Status,
		arg.IsDefault,
		arg.SortOrder,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Icon,
		&i.Color,
		&i.Status,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  user_id, type, amount, currency, description, notes, 
  transaction_date, transaction_id, category_id, account_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, type, amount, currency, description, notes, transaction_date, transaction_id, category_id, account_id, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	UserID          int64          `json:"user_id"`
	Type            string         `json:"type"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	Description     pgtype.Text    `json:"description"`
	Notes           pgtype.Text    `json:"notes"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
	TransactionID   pgtype.UUID    `json:"transaction_id"`
	CategoryID      pgtype.Int8    `json:"category_id"`
	AccountID       pgtype.Int8    `json:"account_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Notes,
		arg.TransactionDate,
		arg.TransactionID,
		arg.CategoryID,
		arg.AccountID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Notes,
		&i.TransactionDate,
		&i.TransactionID,
		&i.CategoryID,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, type, currency, icon, color, status, is_default, sort_order, created_at, updated_at, deleted_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Icon,
		&i.Color,
		&i.Status,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRecentTransactions = `-- name: GetRecentTransactions :many
SELECT id, user_id, type, amount, currency, description, notes, transaction_date, transaction_id, category_id, account_id, created_at, updated_at, deleted_at FROM transactions
WHERE user_id = $1 
  AND deleted_at IS NULL
ORDER BY transaction_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type GetRecentTransactionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// 获取某个用户最近的交易记录，支持分页
func (q *Queries) GetRecentTransactions(ctx context.Context, arg GetRecentTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getRecentTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Notes,
			&i.TransactionDate,
			&i.TransactionID,
			&i.CategoryID,
			&i.AccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByUserId = `-- name: ListAccountsByUserId :many
SELECT id, user_id, name, type, currency, icon, color, status, is_default, sort_order, created_at, updated_at, deleted_at FROM accounts
WHERE user_id = $1 
  AND deleted_at IS NULL
ORDER BY sort_order ASC, created_at DESC
`

func (q *Queries) ListAccountsByUserId(ctx context.Context, userID int64) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Icon,
			&i.Color,
			&i.Status,
			&i.IsDefault,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type SoftDeleteTransactionParams struct {
	ID     int32 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, softDeleteTransaction, arg.ID, arg.UserID)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET 
  name = $2,
  type = $3,
  icon = $4,
  color = $5,
  status = $6,
  is_default = $7,
  sort_order = $8,
  updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, currency, icon, color, status, is_default, sort_order, created_at, updated_at, deleted_at
`

type UpdateAccountParams struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Icon      []byte      `json:"icon"`
	Color     pgtype.Text `json:"color"`
	Status    string      `json:"status"`
	IsDefault bool        `json:"is_default"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
		arg.Status,
		arg.IsDefault,
		arg.SortOrder,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Icon,
		&i.Color,
		&i.Status,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
